name: protopipe
channels:
  - defaults
  - conda-forge
  - cta-observatory
dependencies:
  - ctapipe=0.8.0
  - gammapy=0.8
  - ipython
  - nbsphinx
  - numpydoc
  - pandas
  - pytest
  - sphinx-automodapi
  - sphinx_rtd_theme
  - vitables
