name: protopipe_dev
channels:
  - conda-forge
  - cta-observatory
  - defaults
dependencies:
  - alabaster=0.7.12=py37_0
  - asn1crypto=0.24.0=py37_0
  - astropy=3.2.1=py37h1de35cc_0
  - atomicwrites=1.3.0=py37_1
  - attrs=19.1.0=py37_1
  - babel=2.7.0=py_0
  - blas=1.0=mkl
  - blosc=1.16.3=hd9629dc_0
  - bokeh=1.3.4=py37_0
  - bzip2=1.0.8=h1de35cc_0
  - ca-certificates=2019.9.11=hecc5488_0
  - certifi=2019.9.11=py37_0
  - cffi=1.12.3=py37hb5b8e2f_0
  - chardet=3.0.4=py37_1003
  - click=7.0=py_0
  - corsikaio=0.2.0=pyh1d22016_0
  - cryptography=2.7=py37ha12b0ac_0
  - ctapipe=0.7.0=py_0
  - ctapipe-extra=0.2.18=0
  - cycler=0.10.0=py37_0
  - decorator=4.4.0=py37_1
  - docutils=0.15.2=py37_0
  - eventio=0.20.1=py37h39e3cac_0
  - freetype=2.9.1=hb4e5f40_0
  - gammapy=0.8=py37h1de35cc_1000
  - hdf5=1.10.4=hfa1e0ec_0
  - idna=2.8=py37_0
  - imagesize=1.1.0=py37_0
  - iminuit=1.3.7=py37h6440ff4_0
  - importlib_metadata=0.23=py37_0
  - intel-openmp=2019.4=233
  - ipython_genutils=0.2.0=py37_0
  - jinja2=2.10.1=py37_0
  - joblib=0.13.2=py37_0
  - jpeg=9b=he5867d9_2
  - kiwisolver=1.1.0=py37h0a44026_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libpng=1.6.37=ha441bb4_0
  - libtiff=4.0.10=hcb84e12_2
  - llvm-openmp=4.0.1=hcfea43d_1
  - llvmlite=0.29.0=py37h98b8051_0
  - lz4-c=1.8.1.2=h1de35cc_0
  - lzo=2.10=h362108e_2
  - markupsafe=1.1.1=py37h1de35cc_0
  - matplotlib=3.1.1=py37h54f8f79_0
  - mkl=2019.4=233
  - mkl-service=2.3.0=py37hfbe908c_0
  - mkl_fft=1.0.14=py37h5e564d8_0
  - mkl_random=1.1.0=py37ha771720_0
  - mock=3.0.5=py37_0
  - more-itertools=7.2.0=py37_0
  - ncurses=6.1=h0a44026_1
  - numba=0.45.1=py37h6440ff4_0
  - numexpr=2.7.0=py37h7413580_0
  - numpy=1.17.2=py37h99e6662_0
  - numpy-base=1.17.2=py37h6575580_0
  - olefile=0.46=py37_0
  - openssl=1.1.1d=h1de35cc_2
  - packaging=19.2=py_0
  - pandas=0.25.1=py37h0a44026_0
  - pillow=6.1.0=py37hb68e598_0
  - pip=19.2.3=py37_0
  - pluggy=0.13.0=py37_0
  - psutil=5.6.3=py37h1de35cc_0
  - py=1.8.0=py37_0
  - pycparser=2.19=py37_0
  - pygments=2.4.2=py_0
  - pyhessio=2.1.1=py37h39e3cac_1
  - pyopenssl=19.0.0=py37_0
  - pyparsing=2.4.2=py_0
  - pysocks=1.7.1=py37_0
  - pytables=3.5.2=py37h5bccee9_1
  - pytest=5.2.0=py37_0
  - pytest-arraydiff=0.3=py37h39e3cac_0
  - pytest-astropy=0.5.0=py37_0
  - pytest-doctestplus=0.4.0=py_0
  - pytest-openfiles=0.4.0=py_0
  - pytest-remotedata=0.3.2=py37_0
  - python=3.7.4=h359304d_1
  - python-dateutil=2.8.0=py37_0
  - pytz=2019.2=py_0
  - pyyaml=5.1.2=py37h1de35cc_0
  - readline=7.0=h1de35cc_5
  - regions=0.4=py37heacc8b8_0
  - requests=2.22.0=py37_0
  - scikit-learn=0.21.3=py37h27c97d8_0
  - scipy=1.3.1=py37h1410ff5_0
  - setuptools=41.2.0=py37_0
  - six=1.12.0=py37_0
  - snappy=1.1.7=he62c110_3
  - snowballstemmer=1.9.1=py_0
  - sphinx=2.2.0=py_0
  - sphinx-automodapi=0.12=py_0
  - sphinx_rtd_theme=0.4.3=py_0
  - sphinxcontrib-applehelp=1.0.1=py_0
  - sphinxcontrib-devhelp=1.0.1=py_0
  - sphinxcontrib-htmlhelp=1.0.2=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.2=py_0
  - sphinxcontrib-serializinghtml=1.1.3=py_0
  - sqlite=3.29.0=ha441bb4_0
  - tbb=2019.4=h04f5b5a_0
  - tk=8.6.8=ha441bb4_0
  - tornado=6.0.3=py37h1de35cc_0
  - tqdm=4.36.1=py_0
  - traitlets=4.3.2=py37_0
  - urllib3=1.24.2=py37_0
  - wcwidth=0.1.7=py37_0
  - wheel=0.33.6=py37_0
  - xz=5.2.4=h1de35cc_4
  - yaml=0.1.7=hc338f04_2
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.3.7=h5bba6e5_0
  - pip:
    - imageio==2.5.0
    - networkx==2.3
    - pywavelets==1.0.3
    - pywi==0.3.dev12
    - pywicta==0.4.dev1
    - scikit-image==0.15.0
prefix: /Users/michele/anaconda3/envs/protopipe_dev

